### ISSUE TITLE
Iterative approach to loops

### ISSUE THREAD

**Issue by vadimnazarov** [antigenomics/tcr-pmhc-study#11]
Reinforcement learning:
https://www.nervanasys.com/demystifying-deep-reinforcement-learning/
https://github.com/matthiasplappert/keras-rl

meta-optimization ?

**Comment by mikessh** [comment]
One question to consider here: ``l``th Calpha position is influenced by both ``l-1,l-2,...`` and ``l+1,l+2,...``. We need to somehow apply symmetry here. Note that for CDR3 (but not CDR1 and AG) the ``x[0]==x[L-1] + fixed_value``, where ``L`` is the length. This is known as Omega loop.
